# NumPy Practice

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [7]:
# Create a 1-dimensional NumPy array using np.array()
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Create a 2-dimensional NumPy array using np.array()
b = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])

# Create a 3-dimensional Numpy array using np.array()
c  = np.array([[[1, 2, 3],[4, 5, 6],
                [7, 8, 9], [10, 11, 12]],
                [[13, 14, 15], [16, 17, 18],
                [19, 20, 21], [22, 23, 24]]])

a, b, c

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)


In [4]:
# Attributes of 2-dimensional array


In [5]:
# Attributes of 3-dimensional array


In [11]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(b)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [12]:
# Create an array of shape (10, 2) with only ones
np.ones((10, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0, 100, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [19]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0, 10, (7, 2))

array([[8, 3],
       [4, 9],
       [7, 6],
       [4, 0],
       [2, 1],
       [1, 8],
       [5, 5]], dtype=int32)

In [20]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.rand(3, 5)

array([[0.72918734, 0.42307065, 0.02044786, 0.08073641, 0.63485   ],
       [0.34441336, 0.94414354, 0.14372139, 0.45022938, 0.08101414],
       [0.47106308, 0.26521821, 0.22643631, 0.99242054, 0.62872422]])

In [23]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0, 10, (4, 6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [25]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a = np.random.randint(1, 10, (3, 7))

# Find the unique numbers in the array you just created
a, np.unique(a)

(array([[7, 8, 3, 1, 4, 2, 8],
        [4, 2, 6, 6, 4, 6, 2],
        [2, 4, 8, 7, 9, 8, 5]], dtype=int32),
 array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32))

In [26]:
# Find the 0'th index of the latest array you created
a[0]

array([7, 8, 3, 1, 4, 2, 8], dtype=int32)

In [27]:
# Get the first 2 rows of latest array you created
a[:2]

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2]], dtype=int32)

In [28]:
# Get the first 2 values of the first 2 rows of the latest array
a[:2, :2]

array([[7, 8],
       [4, 2]], dtype=int32)

In [31]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a = np.random.randint(0, 10, (3, 5))
b = np.ones((3, 5))
a, b

(array([[6, 6, 7, 4, 2],
        [7, 5, 2, 0, 2],
        [4, 2, 0, 4, 9]], dtype=int32),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [32]:
# Add the two arrays together
a + b

array([[ 7.,  7.,  8.,  5.,  3.],
       [ 8.,  6.,  3.,  1.,  3.],
       [ 5.,  3.,  1.,  5., 10.]])

In [34]:
# Create another array of ones of shape (5, 3)
c = np.ones((5, 3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
# Try add the array of ones and the other most recent array together
c + b

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [37]:
# Create another array of ones of shape (3, 5)
d = np.ones((3, 5))

In [40]:
# Subtract the new array of ones from the other most recent array
d - c.reshape(3, 5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
# Multiply the ones array with the latest array


In [41]:
# Take the latest array to the power of 2 using '**'
a ** 2

array([[36, 36, 49, 16,  4],
       [49, 25,  4,  0,  4],
       [16,  4,  0, 16, 81]], dtype=int32)

In [42]:
# Do the same thing with np.square()
np.square(a)

array([[36, 36, 49, 16,  4],
       [49, 25,  4,  0,  4],
       [16,  4,  0, 16, 81]], dtype=int32)

In [43]:
# Find the mean of the latest array using np.mean()
np.mean(a)

np.float64(4.0)

In [44]:
# Find the maximum of the latest array using np.max()
np.max(a)

np.int32(9)

In [45]:
# Find the minimum of the latest array using np.min()
np.min(a)

np.int32(0)

In [46]:
# Find the standard deviation of the latest array
np.std(a)

np.float64(2.581988897471611)

In [48]:
# Find the variance of the latest array
np.var(a)

np.float64(6.666666666666667)

In [50]:
# Reshape the latest array to (3, 5, 1)
a.reshape(3, 5, 1)

array([[[6],
        [6],
        [7],
        [4],
        [2]],

       [[7],
        [5],
        [2],
        [0],
        [2]],

       [[4],
        [2],
        [0],
        [4],
        [9]]], dtype=int32)

In [51]:
# Transpose the latest array
a.T

array([[6, 7, 4],
       [6, 5, 2],
       [7, 2, 0],
       [4, 0, 4],
       [2, 2, 9]], dtype=int32)

What does the transpose do?

In [52]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
X1 = np.random.randint(0, 10, (3, 3))
X2 = np.random.randint(0, 10, (3, 2))

In [53]:
# Perform a dot product on the two newest arrays you created
X1 @ X2

array([[ 78, 108],
       [ 87, 102],
       [ 27,  42]], dtype=int32)

In [54]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
X3 = np.random.randint(0, 10, (4, 3))
X4 = np.random.randint(0, 10, (4, 3))

In [55]:
# Perform a dot product on the two newest arrays you created
X3 @ X4

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

It doesn't work. How would you fix it?

In [56]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
X3 @ X4.T

array([[  8,  39,  39,  58],
       [ 32, 128,  86, 143],
       [ 72, 121,  73,  95],
       [ 48, 120,  90, 130]], dtype=int32)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [58]:
# Compare the two arrays with '>'
X3 > X4

array([[ True,  True, False],
       [ True,  True, False],
       [ True, False,  True],
       [False, False,  True]])

What happens when you compare the arrays with `>`?

In [59]:
# Compare the two arrays with '>='
X3 >= X4


array([[ True,  True, False],
       [ True,  True, False],
       [ True, False,  True],
       [False,  True,  True]])

In [61]:
# Find which elements of the first array are greater than 7
X3[X3 > 7]

array([9, 8, 9, 8], dtype=int32)

In [62]:
# Which parts of each array are equal? (try using '==')
X3 == X4


array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])

In [65]:
# Sort one of the arrays you just created in ascending order
X4.sort()
X4

array([[0, 0, 8],
       [3, 8, 8],
       [2, 5, 6],
       [4, 7, 8]], dtype=int32)

In [44]:
# Sort the indexes of one of the arrays you just created


In [67]:
# Find the index with the maximum value in one of the arrays you've created
X4.argmax()

np.int64(2)

In [69]:
# Find the index with the minimum value in one of the arrays you've created
X4.argmax()

np.int64(2)

In [47]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100
