In [1]:
import numpy as np

In [2]:
# Create a 1-D NumPy array with elements 1, 2, 3 and 4
np_array = np.array([1, 2, 3, 4])

In [3]:
# Display the data type of the lements in the NumPy array
np_array.dtype

dtype('int64')

In [4]:
# We can specify the type of data inside the array:
np_array = np.array([1, 2, 3, 4], dtype=np.float32)

In [5]:
np_array.dtype

dtype('float32')

In [6]:
# Upcasting in NumPy arrays
# If we do not specify the type, numpy will choose it for us:
np.array([1, 2, 3.0, 4])

array([1., 2., 3., 4.])

In [8]:
# Multi-dimensional arrays
# Create a 2D NumPy array (matrix) with two rows and four columns
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
# Cell: Array of zeros (1D)
# Create a 1D array of zeros with length 5
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
# Cell: Array of zeros (2D)
# Create a 2D array of zeros with shape (3, 4)
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# Cell: Array of zeros (3D)
# Create a 3D array of zeros with shape (100, 512, 512)
np.zeros((100, 512, 512))

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [13]:
# Cell: Array of ones (1D)
np.ones(5, dtype=np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [14]:
# Cell: Array of ones (2D)
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# Cell: Random numbers in array
np.random.rand(2, 3)

array([[0.69305038, 0.5383349 , 0.83689626],
       [0.2554069 , 0.70395405, 0.21882615]])

In [16]:
# Cell: Array fille with a specific value
# Create a 2x3 array filled with the value 5
np.full((2, 3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [17]:
# Cell: Sequence of numbers (arange)
# Create a 1D array with values from 10 to 25 (step 5)
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [18]:
# Cell: Sequence of numbers with float step
# Create a 1D array with values from 0 to 2 (step 0.3)
np.arange(0, 2, 0.3) # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [19]:
# Cell: Evenly spaced numbers (linspace)
# Create 11 evenly spaced numbers between 0 and 1 (inclusive)
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [20]:
# Cell: Identify matrix
# Create a 3x3 identity matrix (ones on main diagonal)
np.eye(3, k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# Cell: Identity matrix (above main diagonal)
# Create a 3x3 identity matrix with ones above the main diagonal
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [22]:
# Cell: Identity matrix (below main diagonal)
# Create a 3x3 identity matrix with ones below the main diagonal
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
# Cell: Array shape and dimension
# Create 2x3 array and print its dimensions
a = np.array([[5, 10, 15], [20, 25, 30]])
print("Array: " "\n", a)
print("Dimension of the array:", "\n", a.ndim)

Array: 
 [[ 5 10 15]
 [20 25 30]]
Dimension of the array: 
 2


In [26]:
# Cell: Array shape, size and manual size calculation
# Create a 2x3 array and print shape, size, rows and columns
a = np.arange(6).reshape((2, 3))
print("Array:\n", a)
print("Shape of the array: ", a.shape)
print("Number of rows = ", a.shape[0])
print("Number of columns = ", a.shape[1])
print("Size of array: ", a.size)
print("Manual determination of size of array: ", a.shape[0] * a.shape[1])

Array:
 [[0 1 2]
 [3 4 5]]
Shape of the array:  (2, 3)
Number of rows =  2
Number of columns =  3
Size of array:  6
Manual determination of size of array:  6


In [27]:
# Cell: Reshape array
# Reshape a 1D array of 4 elements to 2x2
a = np.array([3, 6, 9, 12])
np.reshape(a, (2, 2))

array([[ 3,  6],
       [ 9, 12]])

In [29]:
# Cell: Reshape with -1
# Reshape a 1D array to 3 rows or 3 columns using -1
a = np.array([3, 6, 9, 12, 15, 18])
print("Three rows: \n", np.reshape(a, (3, -1)))
print("Three columns: \n", np.reshape(a, (-1, 3)))

Three rows: 
 [[ 3  6]
 [ 9 12]
 [15 18]]
Three columns: 
 [[ 3  6  9]
 [12 15 18]]


In [30]:
# Cell: Flatten and Ravel
# Flatten and ravel a 2x2 array and show shapes
a = np.ones((2, 2))
b = a.flatten()
c = a.ravel()
print('Original shape :', a.shape)
print('Array :','\n', a)
print('Shape after flatten :',b.shape)
print('Array :','\n', b)
print('Shape after ravel :',c.shape)
print('Array :','\n', c)

Original shape : (2, 2)
Array : 
 [[1. 1.]
 [1. 1.]]
Shape after flatten : (4,)
Array : 
 [1. 1. 1. 1.]
Shape after ravel : (4,)
Array : 
 [1. 1. 1. 1.]


In [31]:
b[0] = 0
print(a)

[[1. 1.]
 [1. 1.]]


In [34]:
c[0] = 0
print(a)


[[0. 1.]
 [1. 1.]]


In [35]:
# Cell: Array math (addition, ones)
# Create two arrays and add them element-wise
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

In [ ]:
# Cell: Addition
# Add two arrays and print result
add = data + ones
print("Addition of two array:\n", add)

Addition of two array:
 [2 3]


In [37]:
# Cell: Subtraction, multiplication, division
# Subtract, multiply, and divide arrays element-wise
sub = data - ones
print('Subraction of two array:','\n',sub)

#Multiplication:
multi = data*data
print('Multiplication of two array','\n',multi)

#Division:u
div = data/data
print('Division by a constant','\n',div)

Subraction of two array: 
 [0 1]
Multiplication of two array 
 [1 4]
Division by a constant 
 [1. 1.]


In [38]:
# Cell: Mean, std, median
# Calculate mean, standard deviation, and median of array
a = np.arange(5, 15, 2)
print("Mean: ", np.mean(a))
print("Standard deviation: ", np.std(a))
print("Median: ", np.median(a))

Mean:  9.0
Standard deviation:  2.8284271247461903
Median:  9.0


In [43]:
# Cell: Min/Max values along axes
# Find min along columns and max along rows
a = np.array([[1, 6], [4, 3]])

# Minimum along a column
print("Min: ", np.min(a, axis=0))
print("Min: ", np.min(a, axis=1))

# Maximum along a row
print("Max: ", np.max(a, axis=1))
print("Max: ", np.max(a, axis=0))


Min:  [1 3]
Min:  [1 3]
Max:  [6 4]
Max:  [4 6]


In [44]:
# Cell: Sorting arrays
# Sort a 1D array and a 2D array along rows and columns
a = np.array([1, 4, 2, 5, 3, 6, 8, 7, 9])
print("Sorted array:\n", np.sort(a, kind="quicksort"))

b = np.array([[5, 6, 7, 4], [9, 2, 3, 7]])
print("Sort along row:\n"), np.sort(b, kind="mergesort", axis=1)

# Sort along the column
print("Sort along column:\n", np.sort(b, kind="mergesort", axis=0))

Sorted array:
 [1 2 3 4 5 6 7 8 9]
Sort along row:

Sort along column:
 [[5 2 3 4]
 [9 6 7 7]]


In [45]:
# Cell: Slicing 1D arrays
# Slice a 1D array from index 1 to 4
# initial position: included
# final position: excluded
a = np.array([1, 2, 3, 4, 5, 6, 7])
print(a[1:5])

[2 3 4 5]


In [46]:
# Cell: Slicing with step
# Print every third element of array
print(a[::3])

[1 4 7]


In [48]:
# Cell: Slicing with step size
# Print elements with step size 2, odd indices, etc.
# 3rd: step size
print(a[:6:2])
print(a[1::2])
print(a[1:6])

[1 3 5]
[2 4 6]
[2 3 4 5 6]


In [49]:
# Cell: Slicing 2D arrays
# Slice rows and columns of a 2D array
a = np.array([[1,2,3],
              [4,5,6]])
# print first row values
print('First row values :','\n',a[0:1,:])
# with step-size for columns
#print('Alternate values from first row:','\n',a[0:1,::2])
# 
print('Second column values :','\n',a[:,1::2])
print('Arbitrary values :','\n',a[0:1,1:3])

First row values : 
 [[1 2 3]]
Second column values : 
 [[2]
 [5]]
Arbitrary values : 
 [[2 3]]
